### PR TITLE
added support for Highly Reliable Markers in aruco 1.3.0

### PR DESCRIPTION
**Pull request by brinoausrino**
also updated basic example, added example for Highly Reliable Markers and a Highly Reliable Marker Creator

### CODE REVIEW

**Comment by arturoc** [comment]
thanks!

**Comment by arturoc** [comment]
@brinoausrino @frauzufall it seems this is failing for some people: https://forum.openframeworks.cc/t/ofxaruco-broken/28652/1  can you take a look?

**Comment by brinoausrino** [comment]
My mac broke two days ago, so I will have a look next week on the mac issues.

**Comment by arturoc** [comment]
ok, thanks!

**Comment by brinoausrino** [comment]
On my Mac it compiled without any error occuring.

**Pull request merged**
